version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=news_app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/mysql-data

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8282:8080
    depends_on:
    - db

volumes:
  db:
    driver: local
